### ISSUE TITLE
galactic && Detection2D support 

### ISSUE THREAD

**Issue by blackjacket996** [NovoG93/vision_msgs_rviz_plugins#3]
Hey, Does this repo help show Detection2D or only 3D in Rviz2? and support in galactic?

**Comment by NovoG93** [comment]
Hey, the vision_msg definition changed since foxy. 
I assume that the humble branch should work for galactic.
At the moment there is no support for Detection2D msgs

**Comment by blackjacket996** [comment]
> Hey, the vision_msg definition changed since foxy. I assume that the humble branch should work for galactic. At the moment there is no support for Detection2D msgs

yep!It works well in galactic

**Comment by NovoG93** [comment]
Thanks for the feedback
